// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgxufzmbivumjpfbsvtg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxneHVmem1iaXZ1bWpwZmJzdnRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4NjU3ODQsImV4cCI6MjA1NjQ0MTc4NH0.hFhR9WZzKFX3H2IwJpjERBuD0jb2IPjf0iVdr2yxqHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);